@startuml
note as N1
泛型参数
Request: ? extends ActionRequest
Response: ? extends ActionResponse
RequestBuilder: ? extends ActionRequestBuilder
end note

namespace request_builder{
}

namespace response{
    abstract class TransportResponse extends TransportMessage

    class GetResponse extends ActionResponse{
    }

    class GetResult

    class GetField
    class ReplicationResponse extends ActionResponse
    abstract class DocWriteResponse extends ReplicationResponse
    class IndexResponse extends DocWriteResponse
}

namespace action{
    abstract class GenericAction<Request, Response>{
        ---
        // 每一种action有唯一的一个名称。
        +String name()
        // 抽象方法，构造一个Response实例
        +{abstract} Response newResponse()
        // 一些可选的配置
        +public TransportRequestOptions transportOptions(Settings settings)
    }

    abstract class Action<Request,Response,RequestBuilder> extends GenericAction{
        ---
        // 抽象方法，构造一个RequestBuilder
        +{abstract} RequestBuilder newRequestBuilder(ElasticsearchClient client)
    }

    class IndexAction extends Action{
    }

    class GetAction extends Action{
    }

    class XxxAction extends Action{
        // 其他Action.....
    }
}

namespace request{
    interface TaskAwareRequest{
        TODO: ??????
        ---
        +void setParentTask(TaskId taskId)
        +TaskId getParentTask()
        +Task createTask(long id, String type, String action, TaskId parentTaskId)
    }
    abstract class TransportMessage
    abstract class TransportRequest extends TransportMessage implements TaskAwareRequest
    abstract class ActionRequest extends TransportRequest{
        ---
        // 校验
        +{abstract} ActionRequestValidationException validate()
        // 执行完毕后是否保存结果
        +boolean getShouldStoreResult()
    }
    interface IndicesRequest{
        // 所有与一个或多个索引关联的请求都应该实现此接口
        ---
        // 关联的索引名称
        +String[] indices()
        +IndicesOptions indicesOptions()
    }
    abstract class SingleShardRequest extends ActionRequest implements IndicesRequest{
        // 在单个Shard上执行的请求
    }

    class GetRequest extends SingleShardRequest{
    }

    abstract class ReplicationRequest extends ActionRequest implements IndicesRequest{
        // 在一组"主从"上执行的请求
        // 先主分片，然后其他副本分片
    }

    abstract class ReplicatedWriteRequest extends ReplicationRequest implements WriteRequest{
    }

    class IndexRequest extends ReplicatedWriteRequest{
    }
}


@enduml