@startuml

interface CheckedRunnable<E extends Exception>{
    +void run() throws E
}

abstract class SearchPhase implements CheckedRunnable{
    -String name
    ---
    +String getName()
}

class FetchSearchPhase extends SearchPhase{
    此阶段将前一阶段的查询结果合并到一起，并计算topN的结果，
    然后到所有相关的shard上去取回topN hits
}

abstract class InitialSearchPhase extends SearchPhase{
    封装了将请求分发到每个shard上并收集结果的逻辑。
    如果在某个shard上执行失败，则会将请求重新发送到它的其他副本，
    直到这个shard的所有副本都耗尽
    ---
    // 在一个shard上执行
    #{abstract} void executePhaseOnShard(SearchShardIterator shardIt, ShardRouting shard, SearchActionListener listener)
    // 当一个shard上执行成功时调用
    #{abstract} void onShardSuccess(FirstResult result)
    // 当所有任务成功时调用
    #{abstract} void onPhaseDone()
}

abstract class AbstractSearchAsyncAction extends InitialSearchPhase implements SearchPhaseContext{
    ---
    // phase执行完毕后，调用getNextPhase获取下一个phase来执行。
    +{final} void onPhaseDone()
    // 返回下一个要执行的Phase
    #{abstract} SearchPhase getNextPhase(..)
}

class SearchQueryThenFetchAsyncAction extends AbstractSearchAsyncAction{
    ---
    // nextPhase是一个FetchSearchPhase
    #SearchPhase getNextPhase(..)
}

class SearchDfsQueryThenFetchAsyncAction extends AbstractSearchAsyncAction{
}

class CanMatchPreFilterSearchPhase extends AbstractSearchAsyncAction{
}

class ExpandSearchPhase extends SearchPhase{
    此阶段只在查询中有field collapse时才会执行
    ---
}

class DfsQueryPhase extends SearchPhase{
}

interface SearchPhaseContext{
    ---
    // 当前查询的总shard数
    +int getNumShards()
    +SearchTask getTask()
    +SearchRequest getRequest()
    +SearchResponse buildSearchResponse(..)
    +void onPhaseFailure(..)
    +void onShardFailure(..)
    +ShardSearchTransportRequest buildShardSearchRequest(..)
    // 执行下一个phase
    +void executeNextPhase(SearchPhase currentPhase, SearchPhase nextPhase)
}

@enduml