@startuml
abstract class PointsFormat{
    +{abstract} PointsWriter fieldsWriter()
    +{abstract} PointsReader fieldsReader()
}

class Lucene60PointsFormat extends PointsFormat{

}

class Lucene60PointsWriter extends PointsWriter{
    +void writeField(FieldInfo fieldInfo, PointsReader values)
    +void finish()
}

class Lucene60PointsReader extends PointsReader{

}

class BKDWriter{

}

Lucene60PointsFormat -down--> Lucene60PointsWriter
Lucene60PointsFormat -down--> Lucene60PointsReader
Lucene60PointsWriter -down--> BKDWriter
@enduml