@startuml
participant LeafCollector
participant Collector
participant IndexSearcher
participant Query
participant Weight
participant Scorer
participant BulkScorer

autonumber
--> IndexSearcher : search(Query query, int n)
activate IndexSearcher
    activate IndexSearcher
        create Collector
        IndexSearcher --> Collector : new
        IndexSearcher --> Query : rewrite()
        IndexSearcher --> Query : createWeight()
        create Weight
        Query --> Weight : new
        ==遍历每一个segment==
        IndexSearcher --> Collector : getLeafCollector
        activate Collector
            create LeafCollector
            Collector --> LeafCollector : new
        deactivate Collector
        IndexSearcher --> Weight : bulkScorer
        activate Weight
            Weight --> Weight : scorer()
            activate Weight
                create Scorer
                Weight --> Scorer : new
            deactivate Weight
            create BulkScorer
            Weight --> BulkScorer : new
        deactivate Weight
        IndexSearcher --> BulkScorer : score(LeafCollector, Bits acceptDocs)
        ==遍历每一个文档==
        BulkScorer --> LeafCollector : collect()
        LeafCollector --> Scorer : score()
        activate BulkScorer
        deactivate BulkScorer
    deactivate IndexSearcher
deactivate IndexSearcher

@enduml