@startuml
class DocumentsWriterDeleteQueue{
    ---
    // 队尾(最后一个删除操作)
    -Node<?> tail

    -DeleteSlice globalSlice
    -BufferedUpdates globalBufferedUpdates
    ReentrantLock globalBufferLock

    long generation
    AtomicLong nextSeqNo
}

class Node<T> {
    // 下一个元素，单向链表
    Node<?> next
    // 当前Node中的元素
    final T item
}

class DeleteSlice {
    分片
    ---
    Node<?> sliceHead
    Node<?> sliceTail
    ---
    // 调用分片中所有Node的apply方法
    void apply(BufferedUpdates del, int docIDUpto)
    // 重置为一个长度为0的分片
    void reset()
}

@enduml