@startuml
class IndexWriter{
    // 负责创建并维护一个index
    ---
    // original user directory
    -Directory directoryOrig
    // wrapped with additional checks
    -Directory directory
    // how to analyze text
    -Analyzer analyzer
    // increments every time a change is completed
    -AtomicLong changeCount
    // 最后一次提交的changeCount
    -long lastCommitChangeCount
    // 所有 segment 的信息
    -SegmentInfos segmentInfos
    //
    -DocumentsWriter docWriter
    -Queue<Event> eventQueue
    -IndexFileDeleter deleter
    ---
    +long addDocument(doc)
    +long updateDocument(Term term, doc)
    +long deleteDocuments(Term... terms)
    // 触发一次MergePolicy的判定
    +void maybeMerge()
    // 强制触发一次merge
    +void forceMerge(int maxNumSegments)
}

class SegmentInfos{
    已经落地的segment
}

class DocumentsWriter{
    In-memery Buffer
}

IndexWriter *-- SegmentInfos
IndexWriter *-- DocumentsWriter
@enduml