@startuml
class SegmentInfos{
    # <b><font color=red>segment_N文件</font></b>
    -List<SegmentCommitInfo> segments
}

class SegmentCommitInfo{
    包装一个只读的SegmentInfo，
    并提供一些 per-commit fields
    每次commit这些字段都<b><font color=red>可能变化
    ---
    +SegmentInfo info
    // 已删除的文档数
    -int delCount
    // .liv文件的生成序号
    -long delGen
    // FieldInfos的生成序号
    -long fieldInfosGen
    ...
}

class SegmentInfo{
    <b><font color=red>xxx.si文件</font></b>,表示一个segment
    <b><font color=red>不可变对象
    ---
    +String name
    -int maxDoc // 段中文档总数
    +Directory dir // 段存在的位置/目录
    -boolean isCompoundFile // 是否使用复合文件
    -Codec codec //段文件的编码解码器
    -Set<String> setFiles //相关文件
}

SegmentInfos "1" -up--*  "n" SegmentCommitInfo : contains
SegmentCommitInfo -left--*  SegmentInfo : wrap
@enduml