@startuml
note as N1
SegmentReader 与 SegmentCoreReader
SegmentCommitInfo 与 SegmentInfo
... 之间的关系:
一个Segment大部分信息是不可变的，但有少部分信息是可变的,每次commit都可能改变。
(比如：segment中被删除的doc ids)
不可变的信息用SegmentInfo封装，可变的少量信息用SegmentCommitInfo封装，
然后SegmentCommitInfo再持有一个SegmentInfo来表示一个完整的Segment信息。
这样一来，一个SegmentInfo可以被多个SegmentCommitInfo共享使用。
同理，一个SegmentCoreReader可能被多个SegmentReader共享使用。
在IndexReader reopen 的时候，这个特性是非常有用的。
end note

class StandardDirectoryReader{
    ~SegmentInfos segmentInfos
    -SegmentReader[] subReaders
}

class SegmentReader{
    -SegmentCommitInfo si
    -Bits liveDocs
    -int numDocs
    ~SegmentCoreReaders core
    ~SegmentDocValues segDocValues
    ~boolean isNRT
    ~DocValuesProducer docValuesProducer
}

class SegmentCoreReader{
    ~FieldsProducer fields
    ~NormsProducer normsProducer
    ~StoredFieldsReader fieldsReaderOrig
    ~TermVectorsReader termVectorsReaderOrig
    ~FieldInfos coreFieldInfos
}

class SegmentInfos{
    # <b><font color=red>segment_N文件</font></b>
    -List<SegmentCommitInfo> segments
}

class SegmentCommitInfo{
    包装一个只读的SegmentInfo，
    并提供一些 per-commit fields
    每次commit这些字段都可能变化
    ---
    +SegmentInfo info
    // 已删除的文档数
    -int delCount
    // .liv文件的生成序号
    -long delGen
    // FieldInfos的生成序号
    -long fieldInfosGen
    ...
}

class SegmentInfo{
    <b><font color=red>xxx.si文件</font></b>,表示一个segment
    <b><font color=red>不可变对象
    ---
    +String name
    -int maxDoc // 段中文档总数
    +Directory dir // 段存在的位置/目录
    -boolean isCompoundFile // 是否使用复合文件
    -Codec codec //段文件的编码解码器
    -Set<String> setFiles //相关文件
}

class FieldInfos{
    # <b><font color=red>.fnm文件
    -boolean hasFreq
    -boolean hasProx
    -boolean hasPayloads
    -boolean hasOffsets
    -boolean hasVectors
    -boolean hasNorms
    -boolean hasDocValues
    -boolean hasPointValues
    --
    -FieldInfo[] byNumberTable
    -SortedMap<Integer,FieldInfo> byNumberMap
    -HashMap<String,FieldInfo> byName
    -Collection<FieldInfo> values
}

class FieldInfo{
    +String name
    +int number
    -DocValuesType docValuesType
    -boolean storeTermVector
    -boolean omitNorms
    -IndexOptions indexOptions
    -boolean storePayloads
}

class FieldsReader extends FieldsProducer{
    -Map<String,FieldsProducer> fields
    -Map<String,FieldsProducer> formats
}

class BlockTreeTermsReader extends FieldsProducer{
}

class CompressingStoredFieldsReader extends StoredFieldsReader{
    // <b><font color=red>读取.fdx和.fdt文件</font></b>
    -CompressingStoredFieldsIndexReader indexReader
    -IndexInput fieldsStream
}

abstract class TermVectorsReader{
    +Fields get(int doc)
}

class CompressingTermVectorsReader extends TermVectorsReader{
    // <b><font color=red>读取.tvx和.tvd文件</font></b>
    // 这里是重用的.fdx的reader类，二者结构是一致的。
    ~CompressingStoredFieldsIndexReader indexReader
    ~IndexInput vectorsStream
}

class FieldsProducer extends Fields{

}

class Fields{
    +Terms terms(String field)
}

abstract class DocValuesProducer{
    // DocValues
    // <b><font color=red>读取.dvd, .dvm文件</font></b>
}

FieldInfos "1" -left---*  "n" FieldInfo : contains

SegmentCoreReader --* FieldInfos : contains
SegmentCoreReader --* FieldsProducer : contains
SegmentCoreReader --* StoredFieldsReader : contains
SegmentCoreReader --* TermVectorsReader : contains

SegmentReader -up--* SegmentCoreReader : contains
SegmentReader -up--* DocValuesProducer : contains
StandardDirectoryReader "1" -left--* "n" SegmentReader : contains
StandardDirectoryReader -up--* SegmentInfos : contains
SegmentInfos "1" -up--*  "n" SegmentCommitInfo : contains
SegmentCommitInfo -up--*  SegmentInfo : wrap

@enduml
