@startuml

set namespaceSeparator ::

interface ElasticsearchClient{
    // 泛型参数：
    // Request extends ActionRequest
    // Response extends ActionResponse
    // RequestBuilder extends ActionRequestBuilder<Request, Response, RequestBuilder>
    ---
    // action：命令种类   request: 请求参数
    +ActionFuture<Response> execute(Action<Request, Response, RequestBuilder> action, Request request)
    // 同上，listener是收到结果后的回调函数
    +void execute(Action<Request, Response, RequestBuilder> action, Request request, ActionListener<Response> listener)
    // 初始化一个RequestBuilder, 用来构造Request
    +RequestBuilder prepareExecute(Action<Request, Response, RequestBuilder> action)
    // 返回该client用于执行请求的线程池
    ThreadPool threadPool()
}

interface Client extends ElasticsearchClient{
    // 对ES集群操作的一站式接口:
    // 集群层面的操作，索引层面的操作，文档层面的操作。
    ---
    +AdminClient admin()
    +Settings settings()
    // 所有操作都是异步的，有两种形式
    // 1. 返回ActionFuture  2. 回调 Listener
    index
    update
    delete
    bulk
    get
    multiGet
    search
    searchScroll
    clearScroll
    multiSearch
    termVectors
    explain
    fieldCaps
}

abstract class AbstractClient implements Client{
}

interface ClusterAdminClient extends ElasticsearchClient{
    对集群操作
    ---
    health
    state
    updateSettings
    reroute
    nodesInfo
    clusterStats
    listTasks
    getTask
    cancelTasks
}

class AbstractClient.ClusterAdmin implements ClusterAdminClient{
}

interface IndicesAdminClient extends ElasticsearchClient{
    对索引操作
    ---
    exists
    typesExists
    stats
    recoveries
    segments
    shardStores
    create
    delete
    close
    open
    refresh
    flush
    syncedFlush
    forceMerge
    upgrade
    getMappings
    putMapping
    aliases
    getAliases
    clearCache
    updateSettings
    analyze
}

class AbstractClient.IndicesAdmin implements IndicesAdminClient{
}

abstract class TransportClient extends AbstractClient{
}

class NodeClient extends AbstractClient{
    // 在本地Node执行Action
    ---
}

interface AdminClient{
    +ClusterAdminClient cluster()
    +IndicesAdminClient indices()
}

Client -left-- AdminClient
@enduml